version: '3.3'
volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./backend/.env

  backend:
    image: t1max/foodgram-backend:latest
    env_file:
      - ./backend/.env
    depends_on:
    - db

  frontend:
    image: t1max/foodgram_frontend
    env_file: ./backend/.env
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    image: t1max/foodgram_nginx
    env_file: ./backend/.env
    depends_on:
      - frontend
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/usr/share/nginx/html
