"""добавлена модель ингредиентов

Revision ID: 2365b2ded877
Revises: 7a90e97b270c
Create Date: 2025-11-17 22:03:55.360707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2365b2ded877'
down_revision: Union[str, Sequence[str], None] = '7a90e97b270c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('measurement_unit', sa.Enum('GRAM', 'KILOGRAM', 'LITER', 'MILLILITER', 'PIECE', name='measurement_unit_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    # ### end Alembic commands ###
